export default {
    CHANGE_LOGIN_STATUS: 'CHANGE_LOGIN_STATUS',
    CHANGE_USER_INFO: 'CHANGE_USER_INFO',
    CHANGE_ALL_BLOGS: 'CHANGE_ALL_BLOGS',
    CHANGE_USER_BLOGS: 'CHANGE_USER_BLOGS',
    CHANGE_USER_BLOGS_LOADING: 'CHANGE_USER_BLOGS_LOADING',
    CHANGE_ALL_BLOGS_LOADING: 'CHANGE_ALL_BLOGS_LOADING',
    CHANGE_REALOAD_BLOGS: 'CHANGE_REALOAD_BLOGS'
}